@id=7456bda2-24aa-4dfe-b654-966e59eedef7

PUT http://localhost:5093/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "USA Breakfast",
    "description": "generic USA brekfast",
    "startDateTime": "2023-04-30T22:00:00",
    "startDateTime": "2023-04-30T23:00:00",
    "savory": [
        "scrambled eggs",
        "baconXD"
    ],
    "sweets": [
        "pancakes"
    ]
}